version: "3"
services:
  employee-jdbc-container:
    image: employee-jdbc
    ports:
      - "9090:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysql
    restart: always 
  mysql:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  
    volumes:
      - my-datavolume:/var/lib/mysql
networks:
  employee-mysql:
volumes:
  my-datavolume:
