apiVersion: v1
kind: Service
metadata:
  name: employee-jdbc
  labels:
    run: web-service
spec:
  selector:
    app: employee-jdbc
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8080
    nodePort: 30007
